(function (global) {
  const dict = {
    es: {
      language: "Idioma", lang_es: "Español (Paraguay)", lang_pt: "Português (Brasil)", lang_en: "English (Estados Unidos)", loading: "Cargando…", spanish: "Español", portuguese: "Português", english: "English",
      nav_home: "Inicio", nav_share: "Participación", nav_volumes: "Volúmenes", nav_models: "Marcas", nav_trajectories: "Trayectorias", nav_chargers: "Cargadores", nav_vehicles: "Vehículos",
      theme_dark: "Oscuro", theme_light: "Claro", theme_aria: "Cambiar tema", primary_nav: "Principal", page_home: "Paraguay EV Market — importaciones", page_share: "Participación — Paraguay EV Market", page_volumes: "Volúmenes — Paraguay EV Market", page_chargers: "Cargadores DC — Paraguay EV Market", page_trajectories: "Trayectorias — Paraguay EV Market", prev_home: "← Inicio", next_volumes: "Volúmenes →", prev_share: "← Participación", next_home: "Inicio", prev_volumes: "← Volúmenes", next_chargers: "Cargadores →", next_trajectories: "Trayectorias →", prev_trajectories: "← Trayectorias",
      home_title: "Mercado híbrido / eléctrico en Paraguay",
      home_lead: "Seguimiento mensual de las importaciones de vehículos en Paraguay: eléctricos de batería (BEV), híbridos enchufables (PHEV) e híbridos (HEV), comparados con el total y los vehículos de combustión (ICE).",
      home_note: "Serie disponible: enero–septiembre de 2026. Incluye vehículos nuevos y usados.",
      explore: "Explorar", card_share: "Participación (%)", card_share_desc: "Cuota de BEV, PHEV, HEV, OTHERS e ICE dentro del total de vehículos importados.", card_volumes: "Volúmenes (unidades)", card_volumes_desc: "Unidades por categoría y total del mercado para comparar electrificados y combustión.", card_chargers: "Cargadores DC", card_chargers_desc: "Mapa y tabla de 73 ubicaciones y 147 conectores DC. Potencia orientativa · PlugShare, 2 oct 2026.", latest_breakdown: "Último mes — desglose", source_aduana: "Datos: Aduana Nacional del Paraguay.", data_badge: "Aduana PY · datos abiertos", share_badge: "% del total", volumes_badge: "Unidades absolutas", others_mild: "OTHERS (mild)", source_plugshare: "Datos: PlugShare · actualización 2 oct 2026.", inspired: "Inspirado en el espíritu de", not_clone: "— no es un clon.", last_month: "Último mes", units_hs: "unidades",
      share_title: "Participación por tipo de motorización", share_lead: "Participación mensual de cada tipo de motorización dentro del total de vehículos importados. Las barras suman 100 % para facilitar la comparación.", share_axis: "% del total", share_of_total: "del total", month: "Mes", exact_pct: "Tabla — porcentajes exactos", share_note: "Los porcentajes se calculan sobre el total mensual de vehículos importados.", ice_formula: "ICE = total menos BEV, PHEV, HEV y OTHERS.",
      volumes_title: "Volúmenes: total, electrificados e ICE", volumes_lead: "Unidades importadas por mes, con una vista ampliada de los vehículos electrificados y otra con el total del mercado.", electrified: "Electrificados (sin ICE)", electrified_lead: "BEV, PHEV, HEV y OTHERS, sin ICE, para comparar mejor las categorías electrificadas. Cada etiqueta muestra unidades y porcentaje del total.", all_categories: "Todas las categorías (+ ICE)", all_categories_lead: "Comparación de todas las categorías con ICE y TOTAL. El gráfico superior y la tabla ayudan a leer las categorías de menor volumen.", units_categories: "Unidades (categorías)", units_no_ice: "Unidades (sin ICE)", exact_units_pct: "Tabla — unidades y porcentajes exactos", volumes_note: "Los porcentajes representan la participación de cada categoría en el total mensual. ICE es la diferencia entre el total y las categorías electrificadas.", includes_new_used: "Incluye vehículos nuevos y usados.",
      chargers_title: "Cargadores DC en Paraguay", chargers_desc: "Red de cargadores DC en Paraguay (CCS2, CHAdeMO y GB/T). Inventario basado en PlugShare, con potencias estimadas cuando el dato no está publicado.", chargers_badge: "PlugShare · actualización 2 oct 2026", dc_only: "Solo DC", scope_note: "Solo se muestran conectores DC (CCS2, CHAdeMO y GB/T). Los puntos residenciales, privados o de acceso restringido están identificados; el mapa comienza con los puntos de acceso público.", map: "Mapa", access: "Acceso", all: "Todos", public: "Público", restricted: "Restringido", private: "Residencial/privado", power_band: "Rango kW", all_bands: "Todas", breakdown: "Desglose", table: "Tabla", map_aria: "Mapa de cargadores DC", showing: "Mostrando", locations: "ubicaciones", plugs: "conectores DC", power_estimated: "potencia estimada cuando no hay un valor publicado", locations_dc: "Ubicaciones DC", chargers_dc: "cargadores DC", operators: "Operadoras", consolidated_labels: "nombres consolidados", connector_types: "CCS2 / CHAdeMO / GB/T", from_locations: "de {n} ubicaciones", by_power: "Por rango de potencia", by_status: "Por estado", top_operators: "Principales operadoras", name: "Nombre", city: "Ciudad", dept: "Dpto.", plugs_short: "Conectores", max_kw: "kW máx.", band: "Rango", kw_source: "Origen de kW", status: "Estado", access_col: "Acceso", no_value: "—", plugshare_link: "PlugShare →",  connector_chart_title: "Conectores CCS vs GB/T", connector_chart_lead: "Cantidad de conectores DC por estándar, según el inventario filtrado (mismo criterio del mapa y la tabla).", connector_chart_foot: "totales del filtro actual · inventario PlugShare", public_inventory: "Datos: PlugShare · actualización 2 oct 2026.",
      units: "unidades", total: "Total", electrified_short: "Electrificados", source_error: "No se pudo cargar",
      traj_badge: "S-curve · TTM", traj_title: "Trayectorias de adopción", traj_lead: "Curva ajustada (estilo Gallery) sobre la participación mensual observada, más el desglose acumulado en ventana móvil. Con una serie corta la proyección es ilustrativa — no un pronóstico firme.", traj_disclaimer: "Serie corta · el ajuste logístico (logit-lineal) usa solo los meses publicados; la línea punteada es una extrapolación ilustrativa, no un pronóstico firme.", traj_extra_title: "Extrapolación — participación BEV / PHEV / HEV / ICE", traj_extra_lead: "Puntos = meses observados. Línea continua = ajuste sobre lo observado. Línea punteada = proyección si la tendencia logit se mantuviera.", traj_ttm_title: "Participación acumulada (ventana móvil)", traj_ttm_lead: "Cuando hay menos de 12 meses, cada punto usa todos los meses disponibles hasta esa fecha (ventana incompleta). Con 12+ meses pasa a TTM de 12 meses.", traj_note: "No se inventan meses históricos. Los totales vienen de data/Paraguay.csv (Aduana PY). ICE = total − BEV − PHEV − HEV − OTHERS.", traj_axis_share: "% del total (ajustado)", traj_ttm_axis: "Participación TTM 12 meses", traj_ttm_axis_partial: "Participación acumulada (ventana incompleta)", traj_fit: "ajuste", traj_proj: "proyección", traj_window: "ventana", traj_months_short: "meses", traj_observed: "Observado", traj_not_forecast: "no es pronóstico firme", traj_ttm_partial_label: "Ventana incompleta (menos de 12 meses)", traj_ttm_full_label: "TTM 12 meses", traj_available: "disponibles", card_traj: "Trayectorias", card_traj_desc: "Extrapolación tipo S-curve y participación acumulada (TTM) al estilo Gallery.",
      segment_label: "Segmento", segment_leve: "Vehículos livianos", segment_recreativo: "Recreativos", segment_pesado: "Pesados", segment_leve_hint: "Automóviles y similares (livianos).", segment_recreativo_hint: "ATV / UTV y recreativos.", segment_pesado_hint: "Camiones y buses.",
      variant_label: "Serie", variant_whole: "Automóviles y similares", variant_light: "Vehículos livianos + camionetas",
      variant_whole_hint: "Automóviles HS 8703 limpio (sin golf/ATV).",
      variant_light_hint: "HS 8703 limpio + pickups livianos HS 8704 (totales combinados).",
      variant_empty: "Sin datos para esta serie todavía.",
      nav_models: "Marcas", page_models: "Marcas y modelos — Paraguay EV Market",
      models_badge: "Marca · modelo · motorización",
      models_title: "Ventas por marca, modelo y motorización",
      models_lead: "Unidades importadas desglosadas por marca y modelo. Cada fila y barra indica claramente si es BEV, PHEV, HEV, ICE u OTHERS.",
      models_empty: "Todavía no hay el detalle por marca/modelo. Cuando se publiquen los CSV en <code>data/models/</code> (o el ensamblado), esta página se completa sola.",
      models_empty_filter: "Sin filas para estos filtros.",
      models_period: "Mes", models_col_brand: "Marca", models_col_model: "Modelo", models_col_pt: "Motorización",
      models_view_general: "Totales", models_view_brand: "Por marca", models_view_model: "Por modelo",
      models_all_brands: "Todas las marcas", models_all_models: "Todos los modelos",
      models_rows: "{n} filas", models_foot: "Fuente: Aduana PY · detalle marca/modelo. Incluye vehículos nuevos y usados.",
      card_models: "Marcas y modelos", card_models_desc: "Volúmenes por marca, modelo y motorización (BEV / PHEV / HEV / ICE).",
      next_models: "Marcas →", prev_models: "← Marcas"
    },
    pt: {
      language: "Idioma", lang_es: "Español (Paraguay)", lang_pt: "Português (Brasil)", lang_en: "English (Estados Unidos)", loading: "Carregando…", spanish: "Español", portuguese: "Português", english: "English",
      nav_home: "Início", nav_share: "Participação", nav_volumes: "Volumes", nav_models: "Marcas", nav_trajectories: "Trajetórias", nav_chargers: "Carregadores", nav_vehicles: "Veículos",
      theme_dark: "Escuro", theme_light: "Claro", theme_aria: "Alterar tema", primary_nav: "Principal", page_home: "Paraguay EV Market — importações", page_share: "Participação — Paraguay EV Market", page_volumes: "Volumes — Paraguay EV Market", page_chargers: "Carregadores DC — Paraguay EV Market", page_trajectories: "Trajetórias — Paraguay EV Market", prev_home: "← Início", next_volumes: "Volumes →", prev_share: "← Participação", next_home: "Início", prev_volumes: "← Volumes", next_chargers: "Carregadores →", next_trajectories: "Trajetórias →", prev_trajectories: "← Trajetórias",
      home_title: "Mercado híbrido / elétrico no Paraguai", home_lead: "Acompanhamento mensal das importações de veículos no Paraguai: elétricos a bateria (BEV), híbridos plug-in (PHEV) e híbridos (HEV), comparados ao total e aos veículos a combustão (ICE).", home_note: "Série disponível: janeiro–setembro de 2026. Inclui veículos novos e usados.", explore: "Explorar", card_share: "Participação (%)", card_share_desc: "Participação de BEV, PHEV, HEV, OTHERS e ICE no total de veículos importados.", card_volumes: "Volumes (unidades)", card_volumes_desc: "Unidades por categoria e total do mercado para comparar eletrificados e combustão.", card_chargers: "Carregadores DC", card_chargers_desc: "Mapa e tabela com 73 locais e 147 conectores DC. Potência indicativa · PlugShare, 2 out. 2026.", latest_breakdown: "Último mês — detalhamento", source_aduana: "Dados: Aduana Nacional do Paraguai.", data_badge: "Aduana PY · dados abertos", share_badge: "% do total", volumes_badge: "Unidades absolutas", others_mild: "OTHERS (mild)", inspired: "Inspirado no espírito da", not_clone: "— não é um clone.", source_plugshare: "Dados: PlugShare · atualização 2 out. 2026.", last_month: "Último mês", units_hs: "unidades",
      share_title: "Participação por tipo de motorização", share_lead: "Participação mensal de cada tipo de motorização no total de veículos importados. As barras somam 100% para facilitar a comparação.", share_axis: "% do total", share_of_total: "do total", month: "Mês", exact_pct: "Tabela — percentuais exatos", share_note: "Os percentuais são calculados sobre o total mensal de veículos importados.", ice_formula: "ICE = total menos BEV, PHEV, HEV e OTHERS.",
      volumes_title: "Volumes: total, eletrificados e ICE", volumes_lead: "Unidades importadas por mês, com uma visão ampliada dos veículos eletrificados e outra do mercado total.", electrified: "Eletrificados (sem ICE)", electrified_lead: "BEV, PHEV, HEV e OTHERS, sem ICE, para comparar melhor as categorias eletrificadas. Cada rótulo mostra unidades e percentual do total.", all_categories: "Todas as categorias (+ ICE)", all_categories_lead: "Comparação de todas as categorias com ICE e TOTAL. O gráfico superior e a tabela ajudam a ler as categorias de menor volume.", units_categories: "Unidades (categorias)", units_no_ice: "Unidades (sem ICE)", exact_units_pct: "Tabela — unidades e percentuais exatos", volumes_note: "Os percentuais representam a participação de cada categoria no total mensal. ICE é a diferença entre o total e as categorias eletrificadas.", includes_new_used: "Inclui veículos novos e usados.",
      chargers_title: "Carregadores DC no Paraguai", chargers_desc: "Rede de carregadores DC no Paraguai (CCS2, CHAdeMO e GB/T). Inventário baseado no PlugShare, com potências estimadas quando o dado não está publicado.", chargers_badge: "PlugShare · atualização 2 out. 2026", dc_only: "Somente DC", scope_note: "São exibidos apenas conectores DC (CCS2, CHAdeMO e GB/T). Pontos residenciais, privados ou de acesso restrito são identificados; o mapa começa pelos pontos de acesso público.", map: "Mapa", access: "Acesso", all: "Todos", public: "Público", restricted: "Restrito", private: "Residencial/privado", power_band: "Faixa kW", all_bands: "Todas", breakdown: "Detalhamento", table: "Tabela", map_aria: "Mapa de carregadores DC", showing: "Exibindo", locations: "locais", plugs: "conectores DC", power_estimated: "potência estimada quando não há valor publicado", locations_dc: "Locais DC", chargers_dc: "carregadores DC", operators: "Operadoras", consolidated_labels: "nomes consolidados", connector_types: "CCS2 / CHAdeMO / GB/T", from_locations: "de {n} locais", by_power: "Por faixa de potência", by_status: "Por status", top_operators: "Principais operadoras", name: "Nome", city: "Cidade", dept: "Dept.", plugs_short: "Conectores", max_kw: "kW máx.", band: "Faixa", kw_source: "Origem do kW", status: "Status", access_col: "Acesso", no_value: "—", plugshare_link: "PlugShare →", connector_chart_title: "Conectores CCS vs GB/T", connector_chart_lead: "Quantidade de conectores DC por padrão, conforme o inventário filtrado (mesmo critério do mapa e da tabela).", connector_chart_foot: "totais do filtro atual · inventário PlugShare", public_inventory: "Dados: PlugShare · atualização 2 out. 2026.", units: "unidades", total: "Total", electrified_short: "Eletrificados", source_error: "Não foi possível carregar",
      traj_badge: "S-curve · TTM", traj_title: "Trajetórias de adoção", traj_lead: "Curva ajustada (estilo Gallery) sobre a participação mensal observada, mais o detalhamento acumulado em janela móvel. Com série curta a projeção é ilustrativa — não é um prognóstico firme.", traj_disclaimer: "Série curta · o ajuste logístico (logit-linear) usa só os meses publicados; a linha tracejada é uma extrapolação ilustrativa, não um prognóstico firme.", traj_extra_title: "Extrapolação — participação BEV / PHEV / HEV / ICE", traj_extra_lead: "Pontos = meses observados. Linha contínua = ajuste sobre o observado. Linha tracejada = projeção se a tendência logit se mantiver.", traj_ttm_title: "Participação acumulada (janela móvel)", traj_ttm_lead: "Com menos de 12 meses, cada ponto usa todos os meses disponíveis até aquela data (janela incompleta). Com 12+ meses passa a TTM de 12 meses.", traj_note: "Não se inventam meses históricos. Os totais vêm de data/Paraguay.csv (Aduana PY). ICE = total − BEV − PHEV − HEV − OTHERS.", traj_axis_share: "% do total (ajustado)", traj_ttm_axis: "Participação TTM 12 meses", traj_ttm_axis_partial: "Participação acumulada (janela incompleta)", traj_fit: "ajuste", traj_proj: "projeção", traj_window: "janela", traj_months_short: "meses", traj_observed: "Observado", traj_not_forecast: "não é prognóstico firme", traj_ttm_partial_label: "Janela incompleta (menos de 12 meses)", traj_ttm_full_label: "TTM 12 meses", traj_available: "disponíveis", card_traj: "Trajetórias", card_traj_desc: "Extrapolação tipo S-curve e participação acumulada (TTM) no estilo Gallery.",
      segment_label: "Segmento", segment_leve: "Veículos leves", segment_recreativo: "Recreativos", segment_pesado: "Pesados", segment_leve_hint: "Automóveis e similares (leves).", segment_recreativo_hint: "ATV / UTV e recreativos.", segment_pesado_hint: "Caminhões e ônibus.",
      variant_label: "Série", variant_whole: "Automóveis e similares", variant_light: "Veículos leves + picapes",
      variant_whole_hint: "Automóveis HS 8703 limpo (sem golf/ATV).",
      variant_light_hint: "HS 8703 limpo + pickups leves HS 8704 (totais combinados).",
      variant_empty: "Ainda sem dados para esta série.",
      nav_models: "Marcas", page_models: "Marcas e modelos — Paraguay EV Market",
      models_badge: "Marca · modelo · motorização",
      models_title: "Vendas por marca, modelo e motorização",
      models_lead: "Unidades importadas detalhadas por marca e modelo. Cada linha e barra indica claramente se é BEV, PHEV, HEV, ICE ou OTHERS.",
      models_empty: "Ainda não há o detalhe por marca/modelo. Quando forem publicados os CSV em <code>data/models/</code> (ou o arquivo montado), esta página se completa sozinha.",
      models_empty_filter: "Sem linhas para estes filtros.",
      models_period: "Mês", models_col_brand: "Marca", models_col_model: "Modelo", models_col_pt: "Motorização",
      models_view_general: "Totais", models_view_brand: "Por marca", models_view_model: "Por modelo",
      models_all_brands: "Todas as marcas", models_all_models: "Todos os modelos",
      models_rows: "{n} linhas", models_foot: "Fonte: Aduana PY · detalhe marca/modelo. Inclui veículos novos e usados.",
      card_models: "Marcas e modelos", card_models_desc: "Volumes por marca, modelo e motorização (BEV / PHEV / HEV / ICE).",
      next_models: "Marcas →", prev_models: "← Marcas"
    },
    en: {
      language: "Language", lang_es: "Spanish (Paraguay)", lang_pt: "Portuguese (Brazil)", lang_en: "English (United States)", spanish: "Español", portuguese: "Português", english: "English",
      nav_home: "Home", nav_share: "Share", nav_volumes: "Volumes", nav_models: "Brands", nav_trajectories: "Trajectories", nav_chargers: "Chargers", nav_vehicles: "Vehicles", theme_dark: "Dark", theme_light: "Light", theme_aria: "Change theme", primary_nav: "Main", page_home: "Paraguay EV Market — imports", page_share: "Share — Paraguay EV Market", page_volumes: "Volumes — Paraguay EV Market", page_chargers: "DC chargers — Paraguay EV Market", page_trajectories: "Trajectories — Paraguay EV Market", prev_home: "← Home", next_volumes: "Volumes →", prev_share: "← Share", next_home: "Home", prev_volumes: "← Volumes", next_chargers: "Chargers →", next_trajectories: "Trajectories →", prev_trajectories: "← Trajectories",
      language: "Language", loading: "Loading…", spanish: "Español", portuguese: "Português", english: "English",
      home_title: "Hybrid / electric vehicle market in Paraguay", home_lead: "Monthly view of vehicle imports in Paraguay: battery-electric (BEV), plug-in hybrid (PHEV) and hybrid (HEV) vehicles, compared with the total and internal-combustion vehicles (ICE).", home_note: "Series available: January–September 2026. Includes new and used vehicles.", explore: "Explore", card_share: "Share (%)", card_share_desc: "BEV, PHEV, HEV, OTHERS and ICE as a share of total vehicle imports.", card_volumes: "Volumes (units)", card_volumes_desc: "Units by category and total market to compare electrified and combustion vehicles.", card_chargers: "DC chargers", card_chargers_desc: "Map and table of 73 locations and 147 DC connectors. Indicative power · PlugShare, Oct 2, 2026.", latest_breakdown: "Latest month — breakdown", source_aduana: "Data: National Customs of Paraguay.", data_badge: "Paraguay Customs · open data", share_badge: "% of total", volumes_badge: "Absolute units", others_mild: "OTHERS (mild)", inspired: "Inspired by the spirit of", not_clone: "— not a clone.", source_plugshare: "Data: PlugShare · updated Oct 2, 2026.", inspired: "Inspired by the spirit of", not_clone: "— not a clone.", last_month: "Latest month", units_hs: "units",
      share_title: "Share by powertrain", share_lead: "Monthly share of each powertrain within total vehicle imports. Bars add up to 100% for easy comparison.", share_axis: "% of total", share_of_total: "of total", month: "Month", exact_pct: "Table — exact percentages", share_note: "Percentages are calculated against the monthly total of imported vehicles.", ice_formula: "ICE = total minus BEV, PHEV, HEV and OTHERS.",
      volumes_title: "Volumes: total, electrified and ICE", volumes_lead: "Imported units by month, with an enlarged view of electrified vehicles and another view of the total market.", electrified: "Electrified (excluding ICE)", electrified_lead: "BEV, PHEV, HEV and OTHERS without ICE, for clearer comparison. Each label shows units and share of the total.", all_categories: "All categories (+ ICE)", all_categories_lead: "Absolute comparison with ICE and TOTAL. The chart above and the table make smaller categories easier to read.", units_categories: "Units (categories)", units_no_ice: "Units (excluding ICE)", exact_units_pct: "Table — exact units and percentages", volumes_note: "Percentages show each category's share of the monthly total. ICE is the difference between the total and electrified categories.", includes_new_used: "Includes new and used vehicles.",
      chargers_title: "DC chargers in Paraguay", chargers_desc: "DC charging network in Paraguay (CCS2, CHAdeMO and GB/T). Inventory based on PlugShare, with estimated power when no published value is available.", chargers_badge: "PlugShare · updated Oct 2, 2026", dc_only: "DC only", scope_note: "Only DC connectors (CCS2, CHAdeMO and GB/T) are shown. Residential, private and restricted-access points are identified; the map starts with public-access points.", map: "Map", access: "Access", all: "All", public: "Public", restricted: "Restricted", private: "Residential/private", power_band: "Power range", all_bands: "All", breakdown: "Breakdown", table: "Table", map_aria: "Map of DC chargers", showing: "Showing", locations: "locations", plugs: "DC connectors", power_estimated: "power estimated when no published value is available", locations_dc: "DC locations", chargers_dc: "DC chargers", operators: "Operators", consolidated_labels: "consolidated names", connector_types: "CCS2 / CHAdeMO / GB/T", from_locations: "of {n} locations", by_power: "By power range", by_status: "By status", top_operators: "Top operators", name: "Name", city: "City", dept: "Dept.", plugs_short: "Connectors", max_kw: "Max kW", band: "Range", kw_source: "Power source", status: "Status", access_col: "Access", no_value: "—", plugshare_link: "PlugShare →",  connector_chart_title: "CCS vs GB/T connectors", connector_chart_lead: "DC connector counts by standard, using the filtered inventory (same criteria as the map and table).", connector_chart_foot: "current filter totals · PlugShare inventory", public_inventory: "Data: PlugShare · updated Oct 2, 2026.", units: "units", total: "Total", electrified_short: "Electrified", source_error: "Could not load",
      traj_badge: "S-curve · TTM", traj_title: "Adoption trajectories", traj_lead: "Gallery-style fitted curve on observed monthly shares, plus a rolling accumulated split. With a short series the projection is illustrative — not a firm forecast.", traj_disclaimer: "Short series · the logistic (linear-in-logit) fit uses only published months; the dashed line is an illustrative extrapolation, not a firm forecast.", traj_extra_title: "Extrapolation — BEV / PHEV / HEV / ICE share", traj_extra_lead: "Dots = observed months. Solid line = fit on observations. Dashed line = projection if the logit trend continued.", traj_ttm_title: "Accumulated share (rolling window)", traj_ttm_lead: "With fewer than 12 months, each point uses all months available up to that date (incomplete window). With 12+ months it becomes a true 12-month TTM.", traj_note: "No invented historical months. Totals come from data/Paraguay.csv (Paraguay Customs). ICE = total − BEV − PHEV − HEV − OTHERS.", traj_axis_share: "% of total (fitted)", traj_ttm_axis: "12-month trailing share", traj_ttm_axis_partial: "Accumulated share (incomplete window)", traj_fit: "fit", traj_proj: "projection", traj_window: "window", traj_months_short: "months", traj_observed: "Observed", traj_not_forecast: "not a firm forecast", traj_ttm_partial_label: "Incomplete window (under 12 months)", traj_ttm_full_label: "12-month TTM", traj_available: "available", card_traj: "Trajectories", card_traj_desc: "S-curve-style extrapolation and rolling accumulated share (TTM), Gallery-inspired.",
      segment_label: "Segment", segment_leve: "Light vehicles", segment_recreativo: "Recreational", segment_pesado: "Heavy", segment_leve_hint: "Passenger cars and similar (light).", segment_recreativo_hint: "ATV / UTV and recreational.", segment_pesado_hint: "Trucks and buses.",
      variant_label: "Series", variant_whole: "Passenger cars", variant_light: "Light vehicles + pickups",
      variant_whole_hint: "Clean HS 8703 cars (no golf/ATV).",
      variant_light_hint: "Clean HS 8703 + light HS 8704 pickups (combined totals).",
      variant_empty: "No data for this series yet.",
      nav_models: "Brands", page_models: "Brands & models — Paraguay EV Market",
      models_badge: "Brand · model · powertrain",
      models_title: "Sales by brand, model and powertrain",
      models_lead: "Imported units broken down by brand and model. Every row and bar clearly shows whether it is BEV, PHEV, HEV, ICE or OTHERS.",
      models_empty: "Brand/model detail is not published yet. When monthly CSVs land in <code>data/models/</code> (or the assembled file), this page fills in automatically.",
      models_empty_filter: "No rows for these filters.",
      models_period: "Month", models_col_brand: "Brand", models_col_model: "Model", models_col_pt: "Powertrain",
      models_view_general: "Totals", models_view_brand: "By brand", models_view_model: "By model",
      models_all_brands: "All brands", models_all_models: "All models",
      models_rows: "{n} rows", models_foot: "Source: Paraguay Customs · brand/model detail. Includes new and used vehicles.",
      card_models: "Brands & models", card_models_desc: "Volumes by brand, model and powertrain (BEV / PHEV / HEV / ICE).",
      next_models: "Brands →", prev_models: "← Brands"
    }
  };
  let current = "es";
  function t(key, vars) { let s = (dict[current] && dict[current][key]) || dict.es[key] || key; if (vars) Object.keys(vars).forEach(k => { s = s.replaceAll("{" + k + "}", vars[k]); }); return s; }
  function apply() {
    document.documentElement.lang = current;
    document.querySelectorAll("[data-i18n]").forEach(el => { el.innerHTML = t(el.dataset.i18n); });
    document.querySelectorAll("[data-i18n-attr]").forEach(el => { const [attr, key] = el.dataset.i18nAttr.split(":"); el.setAttribute(attr, t(key)); });
    const b = document.getElementById("themeToggle"); if (b) { b.textContent = t(document.documentElement.dataset.theme === "dark" ? "theme_light" : "theme_dark"); b.setAttribute("aria-label", t("theme_aria")); }
    const sel = document.getElementById("languageToggle"); if (sel) {
      const labels = { es: ["🇵🇾 ES", "lang_es"], pt: ["🇧🇷 PT", "lang_pt"], en: ["🇺🇸 EN", "lang_en"] };
      sel.value = current; sel.setAttribute("aria-label", t("language"));
      sel.querySelectorAll("option").forEach(opt => { const item = labels[opt.value]; if (item) { opt.textContent = item[0]; opt.setAttribute("aria-label", t(item[1])); } });
    }
    global.dispatchEvent(new CustomEvent("pyev-lang", { detail: current }));
  }
  function setLanguage(lang) { current = dict[lang] ? lang : "es"; try { localStorage.setItem("pyev-lang", current); } catch (e) {} apply(); }
  try { const saved = localStorage.getItem("pyev-lang"); if (dict[saved]) current = saved; } catch (e) {}
  global.PYEV = global.PYEV || {};
  global.PYEV.t = t; global.PYEV.language = () => current; global.PYEV.setLanguage = setLanguage; global.PYEV.applyLanguage = apply;
  document.addEventListener("DOMContentLoaded", () => { const sel = document.getElementById("languageToggle"); if (sel) sel.addEventListener("change", e => setLanguage(e.target.value)); apply(); });
})(window);
