(function (global) {
  const dict = {
    es: {
      language: "Idioma", lang_es: "Español (Paraguay)", lang_pt: "Português (Brasil)", lang_en: "English (Estados Unidos)", loading: "Cargando…", spanish: "Español", portuguese: "Português", english: "English",
      nav_home: "Inicio", nav_share: "Participación", nav_volumes: "Volúmenes", nav_chargers: "Cargadores",
      theme_dark: "Oscuro", theme_light: "Claro", theme_aria: "Cambiar tema", primary_nav: "Principal", page_home: "Paraguay EV Market — importaciones HS 8703", page_share: "Participación — Paraguay EV Market", page_volumes: "Volúmenes — Paraguay EV Market", page_chargers: "Cargadores DC — Paraguay EV Market", prev_home: "← Inicio", next_volumes: "Volúmenes →", prev_share: "← Participación", next_home: "Inicio", prev_volumes: "← Volúmenes",
      home_title: "Mercado híbrido / eléctrico en Paraguay",
      home_lead: "Seguimiento mensual de las importaciones de vehículos en Paraguay: eléctricos de batería (BEV), híbridos enchufables (PHEV) e híbridos (HEV), comparados con el total y los vehículos de combustión (ICE).",
      home_note: "Serie disponible: agosto y septiembre de 2026. Incluye vehículos nuevos y usados.",
      explore: "Explorar", card_share: "Participación (%)", card_share_desc: "Cuota de BEV, PHEV, HEV, OTHERS e ICE dentro del total de vehículos importados.", card_volumes: "Volúmenes (unidades)", card_volumes_desc: "Unidades por categoría y total del mercado para comparar electrificados y combustión.", card_chargers: "Cargadores DC", card_chargers_desc: "Mapa y tabla de 73 ubicaciones y 147 conectores DC. Potencia orientativa · PlugShare, 2 oct 2026.", latest_breakdown: "Último mes — desglose", source_aduana: "Datos: Aduana Nacional del Paraguay (HS 8703).", data_badge: "Aduana PY · datos abiertos", share_badge: "% del total HS 8703", volumes_badge: "Unidades absolutas", others_mild: "OTHERS (mild)", source_plugshare: "Datos: PlugShare · actualización 2 oct 2026.", inspired: "Inspirado en el espíritu de", not_clone: "— no es un clon.", last_month: "Último mes", units_hs: "unidades HS 8703",
      share_title: "Participación por tipo de motorización", share_lead: "Participación mensual de cada tipo de motorización dentro del total de vehículos importados. Las barras suman 100 % para facilitar la comparación.", share_axis: "% del total HS 8703", share_of_total: "del total", month: "Mes", exact_pct: "Tabla — porcentajes exactos", share_note: "Los porcentajes se calculan sobre el total mensual de vehículos importados.", ice_formula: "ICE = total menos BEV, PHEV, HEV y OTHERS.",
      volumes_title: "Volúmenes: total, electrificados e ICE", volumes_lead: "Unidades importadas por mes, con una vista ampliada de los vehículos electrificados y otra con el total del mercado.", electrified: "Electrificados (sin ICE)", electrified_lead: "BEV, PHEV, HEV y OTHERS, sin ICE, para comparar mejor las categorías electrificadas. Cada etiqueta muestra unidades y porcentaje del total.", all_categories: "Todas las categorías (+ ICE)", all_categories_lead: "Comparación de todas las categorías con ICE y TOTAL. El gráfico superior y la tabla ayudan a leer las categorías de menor volumen.", units_categories: "Unidades (categorías)", units_no_ice: "Unidades (sin ICE)", exact_units_pct: "Tabla — unidades y porcentajes exactos", volumes_note: "Los porcentajes representan la participación de cada categoría en el total mensual. ICE es la diferencia entre el total y las categorías electrificadas.", includes_new_used: "Incluye vehículos nuevos y usados clasificados en HS 8703.",
      chargers_title: "Cargadores DC en Paraguay", chargers_desc: "Red de cargadores DC en Paraguay (CCS2, CHAdeMO y GB/T). Inventario basado en PlugShare, con potencias estimadas cuando el dato no está publicado.", chargers_badge: "PlugShare · actualización 2 oct 2026", dc_only: "Solo DC", scope_note: "Solo se muestran conectores DC (CCS2, CHAdeMO y GB/T). Los puntos residenciales, privados o de acceso restringido están identificados; el mapa comienza con los puntos de acceso público.", map: "Mapa", access: "Acceso", all: "Todos", public: "Público", restricted: "Restringido", private: "Residencial/privado", power_band: "Rango kW", all_bands: "Todas", breakdown: "Desglose", table: "Tabla", map_aria: "Mapa de cargadores DC", showing: "Mostrando", locations: "ubicaciones", plugs: "conectores DC", power_estimated: "potencia estimada cuando no hay un valor publicado", locations_dc: "Ubicaciones DC", chargers_dc: "cargadores DC", operators: "Operadoras", consolidated_labels: "nombres consolidados", connector_types: "CCS2 / CHAdeMO / GB/T", from_locations: "de {n} ubicaciones", by_power: "Por rango de potencia", by_status: "Por estado", top_operators: "Principales operadoras", name: "Nombre", city: "Ciudad", dept: "Dpto.", plugs_short: "Conectores", max_kw: "kW máx.", band: "Rango", kw_source: "Origen de kW", status: "Estado", access_col: "Acceso", no_value: "—", plugshare_link: "PlugShare →", public_inventory: "Datos: PlugShare · actualización 2 oct 2026.",
      units: "unidades", total: "Total", electrified_short: "Electrificados", source_error: "No se pudo cargar"
    },
    pt: {
      language: "Idioma", lang_es: "Español (Paraguay)", lang_pt: "Português (Brasil)", lang_en: "English (Estados Unidos)", loading: "Carregando…", spanish: "Español", portuguese: "Português", english: "English",
      nav_home: "Início", nav_share: "Participação", nav_volumes: "Volumes", nav_chargers: "Carregadores",
      theme_dark: "Escuro", theme_light: "Claro", theme_aria: "Alterar tema", primary_nav: "Principal", page_home: "Paraguay EV Market — importações HS 8703", page_share: "Participação — Paraguay EV Market", page_volumes: "Volumes — Paraguay EV Market", page_chargers: "Carregadores DC — Paraguay EV Market", prev_home: "← Início", next_volumes: "Volumes →", prev_share: "← Participação", next_home: "Início", prev_volumes: "← Volumes",
      home_title: "Mercado híbrido / elétrico no Paraguai", home_lead: "Acompanhamento mensal das importações de veículos no Paraguai: elétricos a bateria (BEV), híbridos plug-in (PHEV) e híbridos (HEV), comparados ao total e aos veículos a combustão (ICE).", home_note: "Série disponível: agosto e setembro de 2026. Inclui veículos novos e usados.", explore: "Explorar", card_share: "Participação (%)", card_share_desc: "Participação de BEV, PHEV, HEV, OTHERS e ICE no total de veículos importados.", card_volumes: "Volumes (unidades)", card_volumes_desc: "Unidades por categoria e total do mercado para comparar eletrificados e combustão.", card_chargers: "Carregadores DC", card_chargers_desc: "Mapa e tabela com 73 locais e 147 conectores DC. Potência indicativa · PlugShare, 2 out. 2026.", latest_breakdown: "Último mês — detalhamento", source_aduana: "Dados: Aduana Nacional do Paraguai (HS 8703).", data_badge: "Aduana PY · dados abertos", share_badge: "% do total HS 8703", volumes_badge: "Unidades absolutas", others_mild: "OTHERS (mild)", inspired: "Inspirado no espírito da", not_clone: "— não é um clone.", source_plugshare: "Dados: PlugShare · atualização 2 out. 2026.", last_month: "Último mês", units_hs: "unidades HS 8703",
      share_title: "Participação por tipo de motorização", share_lead: "Participação mensal de cada tipo de motorização no total de veículos importados. As barras somam 100% para facilitar a comparação.", share_axis: "% do total HS 8703", share_of_total: "do total", month: "Mês", exact_pct: "Tabela — percentuais exatos", share_note: "Os percentuais são calculados sobre o total mensal de veículos importados.", ice_formula: "ICE = total menos BEV, PHEV, HEV e OTHERS.",
      volumes_title: "Volumes: total, eletrificados e ICE", volumes_lead: "Unidades importadas por mês, com uma visão ampliada dos veículos eletrificados e outra do mercado total.", electrified: "Eletrificados (sem ICE)", electrified_lead: "BEV, PHEV, HEV e OTHERS, sem ICE, para comparar melhor as categorias electrificadas. Cada rótulo mostra unidades e percentual do total.", all_categories: "Todas as categorias (+ ICE)", all_categories_lead: "Comparação de todas as categorias com ICE e TOTAL. O gráfico superior e a tabela ajudam a ler as categorias de menor volume.", units_categories: "Unidades (categorias)", units_no_ice: "Unidades (sem ICE)", exact_units_pct: "Tabela — unidades e percentuais exatos", volumes_note: "Os percentuais representam a participação de cada categoria no total mensal. ICE é a diferença entre o total e as categorias electrificadas.", includes_new_used: "Inclui veículos novos e usados classificados em HS 8703.",
      chargers_title: "Carregadores DC no Paraguai", chargers_desc: "Rede de carregadores DC no Paraguai (CCS2, CHAdeMO e GB/T). Inventário baseado no PlugShare, com potências estimadas quando o dado não está publicado.", chargers_badge: "PlugShare · atualização 2 out. 2026", dc_only: "Somente DC", scope_note: "São exibidos apenas conectores DC (CCS2, CHAdeMO e GB/T). Pontos residenciais, privados ou de acesso restrito são identificados; o mapa começa pelos pontos de acesso público.", map: "Mapa", access: "Acesso", all: "Todos", public: "Público", restricted: "Restrito", private: "Residencial/privado", power_band: "Faixa kW", all_bands: "Todas", breakdown: "Detalhamento", table: "Tabela", map_aria: "Mapa de carregadores DC", showing: "Exibindo", locations: "locais", plugs: "conectores DC", power_estimated: "potência estimada quando não há valor publicado", locations_dc: "Locais DC", chargers_dc: "carregadores DC", operators: "Operadoras", consolidated_labels: "nomes consolidados", connector_types: "CCS2 / CHAdeMO / GB/T", from_locations: "de {n} locais", by_power: "Por faixa de potência", by_status: "Por status", top_operators: "Principais operadoras", name: "Nome", city: "Cidade", dept: "Dept.", plugs_short: "Conectores", max_kw: "kW máx.", band: "Faixa", kw_source: "Origem do kW", status: "Status", access_col: "Acesso", no_value: "—", plugshare_link: "PlugShare →", public_inventory: "Dados: PlugShare · atualização 2 out. 2026.", units: "unidades", total: "Total", electrified_short: "Eletrificados", source_error: "Não foi possível carregar"
    },
    en: {
      language: "Language", lang_es: "Spanish (Paraguay)", lang_pt: "Portuguese (Brazil)", lang_en: "English (United States)", spanish: "Español", portuguese: "Português", english: "English",
      nav_home: "Home", nav_share: "Share", nav_volumes: "Volumes", nav_chargers: "Chargers", theme_dark: "Dark", theme_light: "Light", theme_aria: "Change theme", primary_nav: "Main", page_home: "Paraguay EV Market — HS 8703 imports", page_share: "Share — Paraguay EV Market", page_volumes: "Volumes — Paraguay EV Market", page_chargers: "DC chargers — Paraguay EV Market", prev_home: "← Home", next_volumes: "Volumes →", prev_share: "← Share", next_home: "Home", prev_volumes: "← Volumes",
      language: "Language", loading: "Loading…", spanish: "Español", portuguese: "Português", english: "English",
      home_title: "Hybrid / electric vehicle market in Paraguay", home_lead: "Monthly view of vehicle imports in Paraguay: battery-electric (BEV), plug-in hybrid (PHEV) and hybrid (HEV) vehicles, compared with the total and internal-combustion vehicles (ICE).", home_note: "Series available: August and September 2026. Includes new and used vehicles.", explore: "Explore", card_share: "Share (%)", card_share_desc: "BEV, PHEV, HEV, OTHERS and ICE as a share of total vehicle imports.", card_volumes: "Volumes (units)", card_volumes_desc: "Units by category and total market to compare electrified and combustion vehicles.", card_chargers: "DC chargers", card_chargers_desc: "Map and table of 73 locations and 147 DC connectors. Indicative power · PlugShare, Oct 2, 2026.", latest_breakdown: "Latest month — breakdown", source_aduana: "Data: National Customs of Paraguay (HS 8703).", data_badge: "Paraguay Customs · open data", share_badge: "% of HS 8703 total", volumes_badge: "Absolute units", others_mild: "OTHERS (mild)", inspired: "Inspired by the spirit of", not_clone: "— not a clone.", source_plugshare: "Data: PlugShare · updated Oct 2, 2026.", last_month: "Latest month", units_hs: "HS 8703 units",
      share_title: "Share by powertrain", share_lead: "Monthly share of each powertrain within total vehicle imports. Bars add up to 100% for easy comparison.", share_axis: "% of HS 8703 total", share_of_total: "of total", month: "Month", exact_pct: "Table — exact percentages", share_note: "Percentages are calculated against the monthly total of imported vehicles.", ice_formula: "ICE = total minus BEV, PHEV, HEV and OTHERS.",
      volumes_title: "Volumes: total, electrified and ICE", volumes_lead: "Imported units by month, with an enlarged view of electrified vehicles and another view of the total market.", electrified: "Electrified (excluding ICE)", electrified_lead: "BEV, PHEV, HEV and OTHERS without ICE, for clearer comparison. Each label shows units and share of the total.", all_categories: "All categories (+ ICE)", all_categories_lead: "Absolute comparison with ICE and TOTAL. The chart above and the table make smaller categories easier to read.", units_categories: "Units (categories)", units_no_ice: "Units (excluding ICE)", exact_units_pct: "Table — exact units and percentages", volumes_note: "Percentages show each category's share of the monthly total. ICE is the difference between the total and electrified categories.", includes_new_used: "Includes new and used vehicles classified under HS 8703.",
      chargers_title: "DC chargers in Paraguay", chargers_desc: "DC charging network in Paraguay (CCS2, CHAdeMO and GB/T). Inventory based on PlugShare, with estimated power when no published value is available.", chargers_badge: "PlugShare · updated Oct 2, 2026", dc_only: "DC only", scope_note: "Only DC connectors (CCS2, CHAdeMO and GB/T) are shown. Residential, private and restricted-access points are identified; the map starts with public-access points.", map: "Map", access: "Access", all: "All", public: "Public", restricted: "Restricted", private: "Residential/private", power_band: "Power range", all_bands: "All", breakdown: "Breakdown", table: "Table", map_aria: "Map of DC chargers", showing: "Showing", locations: "locations", plugs: "DC connectors", power_estimated: "power estimated when no published value is available", locations_dc: "DC locations", chargers_dc: "DC chargers", operators: "Operators", consolidated_labels: "consolidated names", connector_types: "CCS2 / CHAdeMO / GB/T", from_locations: "of {n} locations", by_power: "By power range", by_status: "By status", top_operators: "Top operators", name: "Name", city: "City", dept: "Dept.", plugs_short: "Connectors", max_kw: "Max kW", band: "Range", kw_source: "Power source", status: "Status", access_col: "Access", no_value: "—", plugshare_link: "PlugShare →", public_inventory: "Data: PlugShare · updated Oct 2, 2026.", units: "units", total: "Total", electrified_short: "Electrified", source_error: "Could not load"
    }
  };
  let current = "es";
  function t(key, vars) { let s = (dict[current] && dict[current][key]) || dict.es[key] || key; if (vars) Object.keys(vars).forEach(k => { s = s.replaceAll("{" + k + "}", vars[k]); }); return s; }
  function apply() {
    document.documentElement.lang = current;
    document.querySelectorAll("[data-i18n]").forEach(el => { el.innerHTML = t(el.dataset.i18n); });
    document.querySelectorAll("[data-i18n-attr]").forEach(el => { const [attr, key] = el.dataset.i18nAttr.split(":"); el.setAttribute(attr, t(key)); });
    const b = document.getElementById("themeToggle"); if (b) { b.textContent = t(document.documentElement.dataset.theme === "dark" ? "theme_light" : "theme_dark"); b.setAttribute("aria-label", t("theme_aria")); }
    const sel = document.getElementById("languageToggle"); if (sel) {
      const labels = { es: ["🇵🇾 ES", "lang_es"], pt: ["🇧🇷 PT", "lang_pt"], en: ["🇺🇸 EN", "lang_en"] };
      sel.value = current; sel.setAttribute("aria-label", t("language"));
      sel.querySelectorAll("option").forEach(opt => { const item = labels[opt.value]; if (item) { opt.textContent = item[0]; opt.setAttribute("aria-label", t(item[1])); } });
    }
    global.dispatchEvent(new CustomEvent("pyev-lang", { detail: current }));
  }
  function setLanguage(lang) { current = dict[lang] ? lang : "es"; try { localStorage.setItem("pyev-lang", current); } catch (e) {} apply(); }
  try { const saved = localStorage.getItem("pyev-lang"); if (dict[saved]) current = saved; } catch (e) {}
  global.PYEV = global.PYEV || {};
  global.PYEV.t = t; global.PYEV.language = () => current; global.PYEV.setLanguage = setLanguage; global.PYEV.applyLanguage = apply;
  document.addEventListener("DOMContentLoaded", () => { const sel = document.getElementById("languageToggle"); if (sel) sel.addEventListener("change", e => setLanguage(e.target.value)); apply(); });
})(window);
